#!/bin/bash
#Author: Atharva Tilewale
#Protein simulation made easy with GRAVITy

# Change working directory
project_dir=$(head -n 1 "/etc/GRAVITy/current_dir.txt")
cd $project_dir
# Source the color script
source /etc/GRAVITy/colors
echo start >$project_dir/run_parameters.conf
source $project_dir/run_parameters.conf
param_file=$project_dir/run_parameters.conf

# Function to stop the spinner if an error occurs
stop_spinner() {
    if [ ! -z "$spinner_pid" ]; then
        kill $spinner_pid
    fi
}

# Function to display a rotating loader with custom text
show_spinner() {
    local pid=$1      # Process ID to monitor
    local message=$2  # Custom loading message
    local spin='-\|/' # Spinner characters
    local i=0

    # Loop to display the spinner until the task completes
    while kill -0 $pid 2>/dev/null; do
        i=$(((i + 1) % 4))
        printf "\r${spin:$i:1} %s..." "$message"
        sleep 0.1
    done
    printf "\r%s...        \n" "$message"
}

#Loaders
#Download loader
download_loader() {
    show_spinner $! "Downloading $file_download_name"
    wait $!
    if [ $? -ne 0 ]; then
        echo -e "${LIGHT_RED}Error: Download failed. Please check your internet connection and try again.${NC}"
        exit 1
    else
        echo -e ${LIGHT_GREEN}$file_download_name "downloaded successfully!"${NC}
        sleep 1.0
    fi
}

pdbfix_loader() {
    show_spinner $! "Fixing PDB File"
    wait $!
    if [ $? -ne 0 ]; then
        echo -e "${LIGHT_RED}Error: Failed to fix PDB file. See log file for more info.${NC}"
        exit 1
    else
        echo -e ${LIGHT_GREEN}"PDB file fixed successfully. Restarting generating protein topology."${NC}
        sleep 3.0
    fi
}

#Energy minimization loader
energy_minimization_loader() {
    show_spinner $! "Running energy minimization"
    wait $!
    if [ $? -ne 0 ]; then
        echo -e "${LIGHT_RED}Error: Failed minimize energy. See log file for more info.${NC}"
        exit 1
    else
        echo -e ${LIGHT_GREEN}"Energy minimized successfully"${NC}
        sleep 1.0
    fi
}

#Equilibration preparation loader
equilibration_preparation_loader() {
    show_spinner $! "Preparing for $equilibration_step_name"
    wait $!
    if [ $? -ne 0 ]; then
        echo -e "${LIGHT_RED}Error: $equilibration_step_name preparation failed. See log file for more info.${NC}"
        exit 1
    else
        echo -e ${LIGHT_GREEN}"$equilibration_step_name preparation successful"${NC}
        sleep 1.0
    fi
}

#Equilibration loader
equilibration_loader() {
    show_spinner $! "Running $equilibration_step_name"
    wait $!
    if [ $? -ne 0 ]; then
        echo -e "${LIGHT_RED}Error: $equilibration_step_name failed. See log file for more info.${NC}"
        exit 1
    else
        echo -e ${LIGHT_GREEN}"$equilibration_step_name done successfully"${NC}
        sleep 1.0
    fi
}

#Box loader
box_loader() {
    show_spinner $! "Preparing Box"
    wait $!
    if [ $? -ne 0 ]; then
        echo -e "${LIGHT_RED}Error: Failed to define the box. See log file for more info.${NC}"
        exit 1
    else
        echo -e ${LIGHT_GREEN}"Box prepared successfully!"${NC}
        sleep 1.0
    fi
}

#Solvate model loader
solvate_loader() {
    show_spinner $! "Solvating the system"
    wait $!
    if [ $? -ne 0 ]; then
        echo -e "${LIGHT_RED}Error: Failed to solvate the system. See log file for more info.${NC}"
        exit 1
    else
        echo -e ${LIGHT_GREEN}"System solvated successfully!"${NC}
        sleep 1.0
    fi
}

#ion tpr loader
ion_tpr_loader() {
    show_spinner $! "Adding ions to the system"
    wait $!
    if [ $? -ne 0 ]; then
        echo -e "${LIGHT_RED}Error: Failed to generate ions.tpr. See log file for more info.${NC}"
        exit 1
    else
        echo -e ${LIGHT_GREEN}"Ions.tpr generated successfully"${NC}
        sleep 1.0
    fi
}

#Ion addition loader
ion_add_loader() {
    show_spinner $! "Adding ions to the system"
    wait $!
    if [ $? -ne 0 ]; then
        echo -e "${LIGHT_RED}Error: Failed to add ions. See log file for more info.${NC}"
        exit 1
    else
        echo -e ${LIGHT_GREEN}"Ions added successfully"${NC}
        sleep 1.0
    fi
}

#check internet connection
check_internet() {
    if ping -c 1 -W 1 8.8.8.8 &>/dev/null; then
        echo -e "Status [${LIGHT_GREEN}Online${NC}]"
    else
        echo -e "Status [${LIGHT_RED}Offline${NC}]"
        echo -e "${LIGHT_RED}It is recommended to connect to the internet while process is going on."
        echo -e "If any dependencies are missing then you may not able to download.${NC}"
    fi
}

# Check if pdbid variable is set and not empty
check_pdbid() {
    if [[ -z "$pdb_id" ]]; then
        echo -e "${LIGHT_RED}No PDB ID provided.${NC}"
        return 1 # PDB ID is not set
    else
        echo -e "PDB ID: ${LIGHT_GREEN}$pdb_id${NC}"
        return 0 # PDB ID is set
    fi
}

#Check dependencies
check_dependencies() {
    command -v gmx >/dev/null 2>&1 || {
        echo -e ${LIGHT_RED} "GROMACS not found. Please install GROMACS and add it to your PATH.${NC}" >&2
        sleep 1.0
        echo "Installing GROMACS..."
        sudo apt-get install gromacs
        exit 1
    }
    command -v obabel >/dev/null 2>&1 || {
        echo -e ${LIGHT_RED} "OpenBabel not found. Please install OpenBabel and add it to your PATH.${NC}" >&2
        sleep 1.0
        echo "Installing openbabel..."
        sudo apt-get install openbabel
        exit 1
    }
    command -v wget >/dev/null 2>&1 || {
        echo -e ${LIGHT_RED} "wget not found. Please install wget to download necessary files.${NC}" >&2
        sleep 1.0
        echo "Installing wget..."
        sudo apt-get install wget
        exit 1
    }
}

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check Python3 and pip3 installation
if command_exists python3; then
    if command_exists pip3; then
        # Check if networkx is installed and its version
        networkx_version=$(pip3 show networkx 2>/dev/null | grep Version | awk '{print $2}')
        if [ -n "$networkx_version" ]; then
            if [ "$networkx_version" == "2.3" ]; then
                echo
            else
                echo "networkx is installed, but version is $networkx_version. Expected version: 2.3"
                echo "Installing networkx v2.3"
                pip3 install networkx==2.3
            fi
        else
            echo "networkx is not installed."
            echo "Installing networkx v2.3"
            pip3 install networkx==2.3
        fi
    else
        echo "pip3 is not installed"
        echo "Installing pip3"
        sudo apt install python3-pip
    fi
else
    echo "Python3 is not installed"
    echo "Installing Python3"
    sudo apt-get install python3
fi

# Function to prompt user for input
prompt_user() {
    read -p "$1" choice
    echo "$choice"
}

# Function to check if a file exists and prompt to overwrite
check_file_exists() {
    local file=$1
    if [ -f "$file" ]; then
        echo -e ${LIGHT_CYAN}"File '$file' already exists."
        while true; do
            read -p "Do you want to continue and overwrite the file? (y/n): " choice
            echo -e ${NC}
            case $choice in
            [Yy]*)
                echo "Proceeding with overwriting the file."
                return 0
                ;;
            [Nn]*)
                echo "Aborting process."
                return 1
                ;;
            *) echo "Please answer yes or no." ;;
            esac
        done
    fi
    return 0
}

# Download protein structure
download_protein() {
    echo -e "${YELLOW}Download protein structure using PDB ID${NC}"
    read -p "Enter PDB ID (e.g., 1HNY): " pdb_id

    # Validate PDB ID format
    if [[ ! "$pdb_id" =~ ^[0-9A-Za-z]{4}$ ]]; then
        echo -e "${LIGHT_RED}Error: Invalid PDB ID format. Please enter a valid 4-character PDB ID.${NC}"
        return 1
    fi

    # Prepare target file path
    local target_file="$project_dir/${pdb_id}.pdb"

    # Attempt download
    echo -e "${CYAN}Downloading PDB structure for ID: $pdb_id...${NC}"
    (wget -q "https://files.rcsb.org/download/${pdb_id}.pdb" -O "$target_file") &
    show_spinner $! "Downloading protein structure"

    # Check download success
    if [[ -s "$target_file" ]]; then
        echo -e "${LIGHT_GREEN}Protein structure downloaded successfully! File saved at: $target_file${NC}"
        mv $target_file $project_dir/protein.pdb
    else
        echo -e "${LIGHT_RED}Error: Failed to download PDB structure. Please verify the PDB ID and your internet connection.${NC}"
        rm -f "$target_file" # Clean up incomplete file
        return 1
    fi
    sleep 1.0
    return 0
}

#Retrieve Complex Molecules
retrieve_complex() {
    check_file_exists "$project_dir/protein.pdb" || return
    check_file_exists "$project_dir/ligand.pdbqt" || return
    echo
    echo -e "Would you like to download the protein structure or enter the path?"
    echo -e "1) Download using PDB ID"
    echo -e "2) Enter the path to the protein structure"
    echo -e "3) Back to main menu"
    read -p "Enter your choice [1-3]: " retrieval_choice

    case $retrieval_choice in
    1) download_protein ;;
    2)
        read -p "Enter the path to your protein file (.pdb): " protein_path
        if [[ ! -f "$protein_path" ]]; then
            echo -e "${LIGHT_RED}Error: $protein_path file does not exist.${NC}"
            return
        else
            cp $protein_path $project_dir/protein.pdb
        fi
        ;;
    3) main_menu ;;
    *)
        echo "Invalid option! Please select between 1 and 4."
        ;;
    esac

    read -p "Enter the path to your ligand file (.pdbqt): " ligand_path
    if [[ ! -f "$ligand_path" ]]; then
        echo -e "${LIGHT_RED}Error: $ligand_path file does not exist.${NC}"
        return
    else
        cp $ligand_path $project_dir/lig.pdbqt
    fi
    if [[ -f "$project_dir/protein.pdb" ]]; then
        if [[ -f "$project_dir/ligand.pdbqt" ]]; then
            echo -e "${LIGHT_GREEN}Molecules retrieved successfully...${NC}"
        fi
    else
        echo -e "${LIGHT_RED}Unable to fetch the molecules, please ensure you enter the correct path...${NC}"
    fi
    echo
}

force_field() {
    echo -e "${LIGHT_BLUE}Select a force field:${NC}"
    PS3="Enter your choice: "
    forcefields=("charmm36" "amber99sb" "charmm27" "gromos54a7" "oplsaa" "Other")
    select ff in "${forcefields[@]}"; do
        case $ff in
        "Other")
            read -p "Enter custom force field: " ff
            break
            ;;
        *)
            break
            ;;
        esac
    done
}

water_model() {
    echo -e "${LIGHT_BLUE}Select a water model:${NC}"
    PS3="Enter your choice: "
    watermodels=("spce" "tip3p" "tip4p" "tip5p" "Other")
    select wm in "${watermodels[@]}"; do
        case $wm in
        "Other")
            read -p "Enter custom water model: " wm
            break
            ;;
        *)
            break
            ;;
        esac
    done
}

# Function to fix PDB file using PDBFixer
pdb_fixer() {
    echo
    if check_internet && check_pdbid; then
        pdbfixer --pdbid="$pdb_id" --keep-heterogens=none --add-residues --replace-nonstandard --add-atoms=all --ph=7.0 --output=$project_dir/protein.pdb --verbose >/dev/null 2>&1 &
        pdbfix_loader
    elif [[ -f "$project_dir/protein.pdb" ]]; then
        pdbfixer protein.pdb --keep-heterogens=none --add-residues --replace-nonstandard --add-atoms=all --ph=7.0 --output=$project_dir/protein.pdb --verbose >/dev/null 2>&1 &
        pdbfix_loader
    else
        echo -e "${LIGHT_RED}Neither protein.pdb file found nor PDBID provided${NC}"
    fi
}

# Function to remove HETATM lines
remove_hetatm() {
    if grep -q "HETATM" $project_dir/protein.pdb; then
        echo "Removing HETATM entries from protein.pdb..."
        sed -i '/^HETATM/d' $project_dir/protein.pdb
    fi
}

# Function to generate protein topology
prepare_protein_topology() {
    # Check auto_check function
    # if [[ $(auto_check) == true ]]; then
    #     remove_hetatm
    #     gmx pdb2gmx -f "$project_dir/protein.pdb" -o "$project_dir/protein.gro" -ff "$ff" -water "$wm" -ignh >/dev/null 2>&1
    #     local exit_status=$?
    #     if [[ $exit_status -ne 0 ]]; then
    #         echo -e "${LIGHT_RED}Error: Failed to generate protein topology. Attempting to fix PDB file.${NC}"
    #         pdb_fixer || {
    #             echo -e "${LIGHT_RED}Error: PDB fixer failed. Exiting.${NC}"
    #             exit 1
    #         }

    #         # Retry GROMACS pdb2gmx after fixing
    #         gmx pdb2gmx -f "$project_dir/protein.pdb" -o "$project_dir/protein.gro" -ff "$ff" -water "$wm" -ignh >/dev/null 2>&1
    #         exit_status=$?
    #         if [[ $exit_status -ne 0 ]]; then
    #             echo -e "${LIGHT_RED}Error: Topology generation failed after fixing.${NC}"
    #             exit 1
    #         fi
    #     fi
    # else
    # Check if protein file exists
    if [[ ! -f "$project_dir/protein.pdb" ]]; then
        echo -e "${LIGHT_RED}Error: protein.pdb file does not exist.${NC}"
        read -p "Do you want to download the protein structure (y/n): " response
        if [[ "$response" == "y" ]]; then
            download_protein || {
                echo -e "${LIGHT_RED}Error: Failed to download protein.${NC}"
                exit 1
            }
        else
            echo -e "${LIGHT_RED}Aborting: No PDB file provided.${NC}"
            exit 1
        fi
    fi

    # Remove HETATM entries
    remove_hetatm
    echo
    force_field
    echo
    water_model

    # Generate protein topology
    echo "Generating Protein Topology..."
    gmx pdb2gmx -f "$project_dir/protein.pdb" -o "$project_dir/protein.gro" -ff "$ff" -water "$wm" -ignh >/dev/null 2>&1
    local exit_status=$?
    if [[ $exit_status -ne 0 ]]; then
        echo -e "${LIGHT_RED}Error: Failed to generate protein topology. Attempting to fix PDB file.${NC}"
        pdb_fixer || {
            echo -e "${LIGHT_RED}Error: PDB fixer failed. Exiting.${NC}"
            exit 1
        }

        # Retry GROMACS pdb2gmx after fixing
        gmx pdb2gmx -f "$project_dir/protein.pdb" -o "$project_dir/protein.gro" -ff "$ff" -water "$wm" -ignh >/dev/null 2>&1
        exit_status=$?
        if [[ $exit_status -ne 0 ]]; then
            echo -e "${LIGHT_RED}Error: Topology generation failed after fixing.${NC}"
            exit 1
        fi
    fi
    # fi

    # Success message
    echo -e "${LIGHT_GREEN}Protein topology generated successfully.${NC}"
    echo
    sleep 1.0
}

prepare_ligand_topology() {
    echo
    echo -e "${YELLOW}------------------------------------"
    echo -e "       Prepare Ligand Topology"
    echo -e "------------------------------------${NC}"
    while true; do
        echo -e "${LIGHT_PURPLE}[${NC}01${LIGHT_PURPLE}]${NC} Prepare .mol2 file"
        echo -e "${LIGHT_PURPLE}[${NC}02${LIGHT_PURPLE}]${NC} Fix .mol2 file"
        echo -e "${LIGHT_PURPLE}[${NC}03${LIGHT_PURPLE}]${NC} Prepare ligand parameter file"
        echo -e "${LIGHT_PURPLE}[${NC}04${LIGHT_PURPLE}]${NC} Generate ligand gro file"
        echo -e "${LIGHT_PURPLE}[${NC}05${LIGHT_PURPLE}]${NC} Generate complex.gro file and edit topol.top"
        echo -e "${LIGHT_PURPLE}[${NC}06${LIGHT_PURPLE}]${NC} Back to Main Menu"
        echo -e "${YELLOW}------------------------------------"
        read -p "Enter your choice [1-6]: " lig_top_choice

        case $lig_top_choice in
        1)
            lig_pdbqt_file="lig.pdbqt"
            if [ ! -f "$lig_pdbqt_file" ]; then
                echo "$lig_pdbqt_file does not exist."
                exit 1
            fi
            if command -v obabel &>/dev/null; then
                check_file_exists "lig.pdb" || return
                obabel lig.pdbqt -O lig.pdb
                if [ -f "lig.pdb" ]; then
                    obabel lig.pdb -O lig.mol2 -h
                    prepare_ligand_topology
                else
                    echo "lig.pdb file does not exits. Please ensure the OpenBabel is properly installed and try again"
                    exit 1
                fi
            else
                echo "Open Babel is not installed. Would you like to install?"
                while true; do
                    echo "Select option"
                    echo "1) YES"
                    echo "2) NO"
                    read -p "Enter your choice [1-2]: " choice

                    case $choice in
                    1)
                        sudo apt-get install obabel
                        ;;
                    2) return ;;
                    esac
                done
                return
            fi
            ;;
        2)
            mol_file="lig.mol2"
            perl_sort_file="sort_mol2_bonds.pl"
            if [ ! -f "$mol_file" ]; then
                if [ ! -f "$perl_sort_file" ]; then
                    echo "$mol_file does not exist."
                    echo "Download the file?"
                    while true; do
                        echo "Select option"
                        echo "1) YES"
                        echo "2) NO"
                        read -p "Enter your choice [1-2]: " choice

                        case $choice in
                        1)
                            wget http://www.mdtutorials.com/gmx/complex/Files/sort_mol2_bonds.pl
                            ;;
                        2) return ;;
                        esac
                    done
                fi
            fi

            if [ -f "$perl_sort_file" ]; then
                check_file_exists "lig_fix.mol2" || return
                perl sort_mol2_bonds.pl lig.mol2 lig_fix.mol2
                sed -i 's/lig\.pdb/LIG/g' lig_fix.mol2
            else
                echo "$perl_sort_file does not exist."
                exit 1
            fi
            echo
            echo "Before proceeding to the next step, generate lig_fix.str file from CGenFF server"
            echo "Login to the server > upload lig_fix.mol2 file > downlaod results lig_fix.str"
            echo
            read -p "Redirecting to the CGenFF webpage. Are you ready? [Y/n] " redirect_check
            case $redirect_check in
            [Yy]*)
                nohup xdg-open "https://app.cgenff.com/homepage" >/dev/null 2>&1 &
                ;;
            [Nn]*)
                echo "Aborting process."
                prepare_ligand_topology
                ;;
            *) echo "Please answer yes or no." ;;
            esac
            ;;
        3)
            if [ ! -f "lig_fix.mol2" ]; then
                echo "lig_fix.mol2 does not exist. Please prepare it first."
                exit 1
            fi
            check_file_exists "lig_fix.prm" || return
            read -p "Enter the path to your lig_fix.str file (.str): " lig_str_path
            if [[ ! -f "$lig_str_path" ]]; then
                echo -e "${LIGHT_RED}Error: $lig_str_path file does not exist.${NC}"
                echo -e "If stream (.str) file is not generated, you can generate it from CGenFF Webserver"
                echo "Login to the server > upload lig_fix.mol2 file > downlaod results lig_fix.str"
                echo
                read -p "Redirecting to the CGenFF webpage. Are you ready? [Y/n] " redirect_check
                case $redirect_check in
                [Yy]*)
                    nohup xdg-open "https://app.cgenff.com/homepage" >/dev/null 2>&1 &
                    ;;
                [Nn]*)
                    echo "Aborting process."
                    prepare_ligand_topology
                    ;;
                *) echo "Please answer yes or no." ;;
                esac
            else
                cp $lig_str_path $project_dir/lig_fix.str
            fi
            python3 cgenff_charmm2gmx_py3_nx2.py LIG lig_fix.mol2 lig_fix.str charmm36.ff || {
                echo "Error: Failed to prepare ligand parameter file."
                exit 1
            }
            prepare_ligand_topology
            ;;
        4)
            if [ ! -f "lig_ini.pdb" ]; then
                echo "lig_ini.pdb does not exist."
                exit 1
            fi
            check_file_exists "lig.gro" || return
            gmx editconf -f lig_ini.pdb -o lig.gro || {
                echo "Error: Failed to prepare ligand topology."
                exit 1
            }
            prepare_ligand_topology
            ;;
        5)
            echo "Generating complex.gro file..."
            if [ ! -f "protein.gro" ]; then
                echo "protein.gro does not exist. Please prepare it first."
                exit 1
            fi
            if [ ! -f "lig.gro" ]; then
                echo "lig.gro does not exist. Please prepare it first."
                exit 1
            fi
            python3 merge.py || {
                echo "Error: Failed to generate complex.gro."
                exit 1
            }
            echo "complex.gro generated successfully."

            # Integrate program 2 to edit topol.top file
            echo "Editing topol.top file..."

            if [ ! -f "topol.top" ]; then
                echo "topol.top does not exist."
                exit 1
            fi

            # Add an empty line and 'lig.itp' after two lines following 'posre.itp'
            sed -i '/#include "posre.itp"/{n;a\
\
; Include ligand topology\
#include "lig.itp"
}' topol.top

            # Add ligand parameters inclusion
            sed -i '/; Include forcefield parameters/{n;a\
\
; Include ligand parameters\
#include "lig.prm"
}' topol.top

            # Add ligand entry at the end
            echo "LIG                 1" >>topol.top

            echo "topol.top file updated successfully."

            # Return to main menu after successful processing
            prepare_ligand_topology
            ;;
        6)
            main_menu
            ;;
        *)
            echo "Invalid option! Please select between 1 and 4."
            ;;
        esac
    done
}

# Function to define box and solvate the system
define_box_and_solvate() {
    echo
    echo "Defining box and solvating system..."
    echo
    if [ ! -f "$project_dir/complex.gro" ]; then
        echo -e ${LIGHT_RED} "complex.gro does not exist.${NC}"
        sleep 2.0
        exit 1
    fi
    check_file_exists "$project_dir/solv.gro" || return
    echo -e ${YELLOW}
    read -p "Do you want to continue with the default box type and solvation model (Cubic/SPC)? (y/n): " select_solvate_box
    echo -e ${NC}
    if [ $select_solvate_box == "y" ]; then
        gmx editconf -f $project_dir/complex.gro -o $project_dir/newbox.gro -c -d 1.0 -bt cubic >/dev/null 2>&1 &
        box_loader
        echo
        gmx solvate -cp $project_dir/newbox.gro -cs spc216.gro -p $project_dir/topol.top -o $project_dir/solv.gro >/dev/null 2>&1 &
        solvate_loader
    else
        echo -e ${YELLOW}"Select box type from the following${NC}"
        echo -e "${LIGHT_PURPLE}[${NC}01${LIGHT_PURPLE}]${NC} Cubic"
        #echo -e "${LIGHT_PURPLE}[${NC}02${LIGHT_PURPLE}]${NC} Octahedral"
        echo -e "${LIGHT_PURPLE}[${NC}02${LIGHT_PURPLE}]${NC} Dodecahedron"
        echo -e "${LIGHT_PURPLE}[${NC}03${LIGHT_PURPLE}]${NC} Triclinic"
        choice=$(prompt_user "Enter your choice [1-3]: ")
        echo -e ${NC}

        case $choice in
        1)
            gmx editconf -f $project_dir/complex.gro -o $project_dir/newbox.gro -c -d 1.0 -bt cubic >/dev/null 2>&1 &
            box_loader
            ;;
        #2) gmx editconf -f protein.gro -o newbox.gro -c -d 1.0 -bt octahedral || { echo -e ${LIGHT_RED} "Error: Failed to define the box.${NC}"
        #sleep 2.0; exit 1; } ;;
        2)
            gmx editconf -f $project_dir/complex.gro -o $project_dir/newbox.gro -c -d 1.0 -bt dodecahedron >/dev/null 2>&1 &
            box_loader
            ;;
        3)
            gmx editconf -f $project_dir/complex.gro -o $project_dir/newbox.gro -c -d 1.0 -bt triclinic >/dev/null 2>&1 &
            box_loader
            ;;
        *)
            echo -e "${LIGHT_RED}Invalid option! Please select between 1 and 3.${NC}"
            sleep 1.0
            ;;
        esac
        echo
        echo -e ${YELLOW}"Select solvation model from the following${NC}"
        echo -e "${LIGHT_PURPLE}[${NC}01${LIGHT_PURPLE}]${NC} SPC"
        #echo -e "${LIGHT_PURPLE}[${NC}02${LIGHT_PURPLE}]${NC} SPC/E"
        echo -e "${LIGHT_PURPLE}[${NC}02${LIGHT_PURPLE}]${NC} TIP3P"
        echo -e "${LIGHT_PURPLE}[${NC}03${LIGHT_PURPLE}]${NC} TIP4P"
        choice=$(prompt_user "Enter your choice [1-3]: ")
        echo -e ${NC}

        case $choice in
        1)
            gmx solvate -cp $project_dir/newbox.gro -cs spc216.gro -p $project_dir/topol.top -o $project_dir/solv.gro >/dev/null 2>&1 &
            solvate_loader
            ;;
        #2) gmx solvate -cp newbox.gro -cs spce216.gro -p topol.top -o solv.gro || { echo -e ${LIGHT_RED} "Error: Failed to solvate the system.${NC}"
        #sleep 2.0; exit 1; } ;;
        2)
            gmx solvate -cp $project_dir/newbox.gro -cs tip3p.gro -p $project_dir/topol.top -o $project_dir/solv.gro >/dev/null 2>&1 &
            solvate_loader
            ;;
        3)
            gmx solvate -cp $project_dir/newbox.gro -cs tip4p.gro -p $project_dir/topol.top -o $project_dir/solv.gro >/dev/null 2>&1 &
            solvate_loader
            ;;
        *)
            echo -e "${LIGHT_RED}Invalid option! Please select between 1 and 3.${NC}"
            sleep 1.0
            ;;
        esac
    fi
}

# Function to add ions
add_ions() {
    if [ ! -f "$project_dir/solv.gro" ]; then
        echo -e ${LIGHT_RED} "solv.gro does not exist."${NC}
        sleep 2.0
        exit 1
    fi

    if [ ! -f "$project_dir/ions.mdp" ]; then
        echo "ions.mdp file does not exist."
        file_download_name="ions.mdp"
        (wget -nc "http://www.mdtutorials.com/gmx/lysozyme/Files/ions.mdp" >/dev/null 2>&1) &
        download_loader
    fi
    echo
    check_file_exists "$project_dir/solv_ions.gro" || return
    gmx grompp -f $project_dir/ions.mdp -c $project_dir/solv.gro -p $project_dir/topol.top -o $project_dir/ions.tpr >/dev/null 2>&1 &
    ion_tpr_loader
    echo -e ${LIGHT_YELLOW}
    read -p "Do you want to continue with the default ions (Both Na+ and Cl-)? (y/n): " select_ion_addition
    echo -e ${NC}
    if [ $select_ion_addition == "y" ]; then
        printf "15\n" | gmx genion -s $project_dir/ions.tpr -o $project_dir/solv_ions.gro -p $project_dir/topol.top -pname NA -nname CL -neutral >/dev/null 2>&1 &
        ion_add_loader
    else
        echo -e ${YELLOW}"Select box type from the following${NC}"
        echo -e "${LIGHT_PURPLE}[${NC}01${LIGHT_PURPLE}]${NC} Add Na+ and Cl- ions to neutralize the system"
        echo -e "${LIGHT_PURPLE}[${NC}02${LIGHT_PURPLE}]${NC} Add only Na+ ions"
        echo -e "${LIGHT_PURPLE}[${NC}03${LIGHT_PURPLE}]${NC} Add only Cl- ions"
        choice=$(prompt_user "Enter your choice [1-3]: ")
        echo -e ${NC}

        case $choice in
        1)
            printf "13\n" | gmx genion -s $project_dir/ions.tpr -o $project_dir/solv_ions.gro -p $project_dir/topol.top -pname NA -nname CL -neutral >/dev/null 2>&1 &
            ion_add_loader
            ;;
        2)
            gmx genion -s $project_dir/ions.tpr -o $project_dir/solv_ions.gro -p $project_dir/topol.top -pname NA >/dev/null 2>&1 &
            ion_add_loader
            ;;
        3)
            gmx genion -s $project_dir/ions.tpr -o $project_dir/solv_ions.gro -p $project_dir/topol.top -nname CL >/dev/null 2>&1 &
            ion_add_loader
            ;;
        *)
            echo -e "${LIGHT_RED}Invalid option! Please select between 1 and 3.${NC}"
            sleep 1.0
            ;;
        esac
    fi
}

# Function to run energy minimization
energy_minimization() {
    # echo "Running energy minimization..."
    if [ ! -f "solv_ions.gro" ]; then
        echo "solv_ions.gro does not exist."
        exit 1
    fi

    if [ ! -f "em.mdp" ]; then
        echo "em.mdp does not exist. Downloading..."
        (wget -nc http://www.mdtutorials.com/gmx/complex/Files/em.mdp) &
        download_loader
    fi

    check_file_exists "em.tpr" || return
    gmx grompp -f $project_dir/em.mdp -c $project_dir/solv_ions.gro -p $project_dir/topol.top -o $project_dir/em.tpr >/dev/null 2>&1 &
    show_spinner $! "Preparing"
    # || { echo "Error: Failed to prepare for energy minimization."; exit 1; }
    check_file_exists "em.gro" || return
    gmx mdrun -v -deffnm $project_dir/em >/dev/null 2>&1 &
    energy_minimization_loader
    echo
    # || { echo "Error: Energy minimization failed."; exit 1; }
}

NVT_equilibration() {
    equilibration_step_name="NVT equilibration"
    gmx grompp -f $project_dir/nvt.mdp -c $project_dir/em.gro -r $project_dir/em.gro -p $project_dir/topol.top -n $project_dir/index.ndx -o $project_dir/nvt.tpr -maxwarn 1 >/dev/null 2>&1 &
    equilibration_preparation_loader
    echo
    gmx mdrun -deffnm $project_dir/nvt -v >/dev/null 2>&1 &
    equilibration_loader
    echo
}

NPT_equilibration() {
    equilibration_step_name="NPT equilibration"
    gmx grompp -f $project_dir/npt.mdp -c $project_dir/nvt.gro -r $project_dir/nvt.gro -t $project_dir/nvt.cpt -p $project_dir/topol.top -n $project_dir/index.ndx -o $project_dir/npt.tpr -maxwarn 1 >/dev/null 2>&1 &
    equilibration_preparation_loader
    echo
    gmx mdrun -deffnm $project_dir/npt -v >/dev/null 2>&1 &
    equilibration_loader
    echo
}

update_eq_steps() {
    #User input simulation time
    echo -e ${YELLOW}"Do you want to continue with default equilibration time (100ps)?"
    echo -e "${LIGHT_PURPLE}[${NC}01${LIGHT_PURPLE}]${NC} Yes, continue"
    echo -e "${LIGHT_PURPLE}[${NC}02${LIGHT_PURPLE}]${NC} No, enter custom value (in ps)"
    echo
    read -p "Enter your choice [1-2]: " eq_time
    echo -e ${NC}
    case $eq_time in
    1) eq_nsteps=50000 ;;
    2)
        # Custom equilibration time in ps
        read -p "Set simulation time in picoseconds (ps): " eq_time_ps
        if [[ "$eq_time_ps" =~ ^[0-9]+$ && "$eq_time_ps" -gt 0 ]]; then
            eq_nsteps=$(echo "$eq_time_ps / 0.002" | bc)
            echo "Custom equilibration time of ${eq_time_ps} ps selected (${eq_nsteps} steps)."
        else
            echo -e "${LIGHT_RED}Invalid input! Please enter a positive numeric value for time in ps.${NC}"
            sleep 2.0
            return
        fi
        ;;
    *)
        echo -e "${LIGHT_RED}Invalid option! Please select between 1 and 3.${NC}"
        sleep 2.0
        return
        ;;
    esac

    # Update nsteps in nvt.mdp and npt.mdp
    sed -i "s/^nsteps.*/nsteps = $eq_nsteps/" $project_dir/nvt.mdp
    sed -i "s/^nsteps.*/nsteps = $eq_nsteps/" $project_dir/npt.mdp
    # echo "Updated nsteps in nvt and npt.mdp:"
    # grep "nsteps" nvt.mdp and npt.mdp  # Verify the update in nvt and npt.mdp

    # Clear old .tpr file (optional but recommended)
    rm -f $project_dir/nvt.tpr
    rm -f $project_dir/npt.tpr
}

# Function to run equilibrium
equilibrium() {
    while true; do
        echo
        echo -e "${YELLOW}--------------------------"
        echo -e "      Equilibrium Menu"
        echo -e "--------------------------${NC}"
        echo -e "${LIGHT_PURPLE}[${NC}01${LIGHT_PURPLE}]${NC} Ligand Restraining"
        echo -e "${LIGHT_PURPLE}[${NC}02${LIGHT_PURPLE}]${NC} Thermostats"
        echo -e "${LIGHT_PURPLE}[${NC}03${LIGHT_PURPLE}]${NC} NVT Equilibration"
        echo -e "${LIGHT_PURPLE}[${NC}04${LIGHT_PURPLE}]${NC} NPT Equilibration"
        echo -e "${LIGHT_PURPLE}[${NC}05${LIGHT_PURPLE}]${NC} Both NVT & NPT"
        echo -e "${LIGHT_PURPLE}[${NC}06${LIGHT_PURPLE}]${NC} Back to Main Menu"
        echo -e "--------------------------${NC}"
        read -p "Enter your choice [1-6]: " equil_choice

        case $equil_choice in
        1)
            echo "Ligand restraining..."
            if [ ! -f "lig.gro" ]; then
                echo "lig.gro does not exist."
                exit 1
            fi
            check_file_exists "index_lig.ndx" || return
            echo -e "0 & ! a H*\nq" | gmx make_ndx -f "lig.gro" -o "index_lig.ndx" >/dev/null 2>&1 || {
                echo "Error: Failed to create index file."
                exit 1
            }
            check_file_exists "posre_lig.itp" || return
            printf "3" | gmx genrestr -f "lig.gro" -n "index_lig.ndx" -o "posre_lig.itp" -fc 1000 1000 1000 >/dev/null 2>&1 || {
                echo "Error: Failed to generate position restraints."
                exit 1
            }
            echo "Ligand restraining completed."

            # Integrate program 2 to edit topol.top file
            echo "Editing topol.top file..."

            if [ ! -f "topol.top" ]; then
                echo "topol.top does not exist."
                exit 1
            fi

            # Add an empty line and 'lig.itp' after two lines following 'posre.itp'
            sed -i '/#include "lig.itp"/{n;a\
; Ligand position restraints\
#ifdef POSRES_LIG\
#include "posre_lig.itp"\
#endif
}' topol.top

            echo "topol.top file updated successfully."
            ;;

        2)
            echo "Setting up thermostats..."
            if [ ! -f "em.gro" ]; then
                echo "em.gro does not exist."
                exit 1
            fi
            check_file_exists "index.ndx" || return
            echo -e "1 | 13 \nq" | gmx make_ndx -f em.gro -o index.ndx >/dev/null 2>&1 || {
                echo "Error: Failed to create index file for thermostats."
                exit 1
            }
            echo "Thermostats setup completed."
            ;;
        3)
            if [ ! -f "$project_dir/em.gro" ]; then
                echo -e ${LIGHT_RED} "em.gro does not exist."${NC}
                sleep 2.0
                exit 1
            fi

            if [ ! -f "$project_dir/nvt.mdp" ]; then
                echo "nvt.mdp does not exist. Downloading..."
                file_download_name="nvt.mdp"
                (wget -nc "http://www.mdtutorials.com/gmx/lysozyme/Files/nvt.mdp") &
                download_loader
            fi

            check_file_exists "$project_dir/nvt.gro" || return

            update_eq_steps
            NVT_equilibration
            ;;
        4)
            if [ ! -f "$project_dir/nvt.gro" ]; then
                echo -e ${LIGHT_RED} "nvt.gro does not exist."${NC}
                exit 1
            fi

            if [ ! -f "$project_dir/npt.mdp" ]; then
                echo "npt.mdp does not exist. Downloading..."
                file_download_name="npt.mdp"
                (wget -nc "http://www.mdtutorials.com/gmx/lysozyme/Files/npt.mdp") &
                download_loader
            fi

            check_file_exists "$project_dir/npt.gro" || return

            update_eq_steps
            NPT_equilibration
            ;;
        5)
            if [ ! -f "$project_dir/em.gro" ]; then
                echo -e ${LIGHT_RED} "em.gro does not exist."${NC}
                sleep 2.0
                exit 1
            fi

            if [ ! -f "$project_dir/nvt.mdp" ]; then
                echo "nvt.mdp does not exist. Downloading..."
                file_download_name="nvt.mdp"
                (wget -nc "http://www.mdtutorials.com/gmx/lysozyme/Files/nvt.mdp") &
                download_loader
            fi
            if [ ! -f "$project_dir/npt.mdp" ]; then
                echo "npt.mdp does not exist. Downloading..."
                file_download_name="npt.mdp"
                (wget -nc "http://www.mdtutorials.com/gmx/lysozyme/Files/npt.mdp") &
                download_loader
            fi

            # Run NVT and NPT in the background, suppress both stdout and stderr
            # Run NVT and NPT in the background, suppressing output, but show loader
            update_eq_steps
            NVT_equilibration
            NPT_equilibration
            sleep 1.0
            # Wait for both NVT and NPT processes to finish
            wait
            return
            ;;
        6)
            echo "Returning to main menu..."
            return
            ;;
        *)
            echo "Invalid option! Please select between 1 and 5."
            ;;
        esac
    done
}

# Update nsteps in md.mdp and regenerate md.tpr
update_simulation_steps() {
    # Update nsteps in md.mdp
    sed -i "s/^nsteps.*/nsteps = $md_nsteps/" $project_dir/md.mdp

    # Clear old .tpr file (optional but recommended)
    rm -f $project_dir/md.tpr

    # Regenerate md.tpr using the updated md.mdp
    gmx grompp -f $project_dir/md.mdp -c $project_dir/npt.gro -p $project_dir/topol.top -n $project_dir/index.ndx -o $project_dir/md.tpr >/dev/null 2>&1 || {
        echo -e ${LIGHT_RED} "Error: Failed to prepare production MD.${NC}"
        exit 1
    }
}

result_analyze(){
    #Recentering and Rewrapping Coordinates...
    if [ ! -f "$project_dir/md.xtc" ]; then
        echo -e ${LIGHT_RED} "md.xtc does not exist.${NC}"
        exit 1
    fi
    check_file_exists "$project_dir/md_center.xtc" || return
    printf "1 0\n" | gmx trjconv -s $project_dir/md.tpr -f $project_dir/md.xtc -o $project_dir/md_center.xtc -pbc mol -center -ur compact >/dev/null 2>&1 || exit 1
    printf "1 0\n" | gmx trjconv -s $project_dir/md.tpr -f $project_dir/md_center.xtc -o $project_dir/md_fit.xtc -fit rot+trans >/dev/null 2>&1 || exit 1

    #Finding RMSD...
    if [ ! -f "$project_dir/md_center.xtc" ]; then
        echo -e ${LIGHT_RED} "md_center.xtc does not exist.${NC}"
        exit 1
    fi
    check_file_exists "$project_dir/rmsd.xvg" || return
    printf "4 4\n" | gmx rms -s $project_dir/em.tpr -f $project_dir/md_center.xtc -n $project_dir/index.ndx -tu ns -o $project_dir/rmsd.xvg >/dev/null 2>&1 || exit 1

    #Extract frames
    sim_time=($md_nsteps*0.002)
    # Ensure sim_time is set
    if [ -z "$sim_time" ]; then
        echo "Error: sim_time is not set."
        exit 1
    else
        # Convert sim_time from ns to ps and ensure it's an integer
        simulation_time=$(echo "$sim_time * 1000" | bc | awk '{printf "%.0f", $1}')

        if [ -z "$sim_frames" ]; then
            if [ "$simulation_time" -ge 100 ]; then
                # Determine interval based on sim_time
                if [ "$simulation_time" -gt 100000 ]; then
                    interval=50000  # 50 ns
                elif [ "$simulation_time" -gt 10000 ]; then
                    interval=5000   # 5 ns
                elif [ "$simulation_time" -gt 1000 ]; then
                    interval=500    # 500 ps
                else
                    interval=100    # 100 ps
                fi

                # Ensure frames directory exists
                frames_dir="frames"
                mkdir -p "$frames_dir"

                # Initialize the start time
                start_time=0

                # Loop through the time steps and extract frames
                while [ $start_time -le $simulation_time ]; do
                    # Here you can call the command to extract the frame, e.g.:
                    printf "17\n" | gmx trjconv -s md.tpr -f md_center.xtc -o $frames_dir/frame_${start_time}.pdb -b $start_time -e $start_time
                    ((start_time+=interval))
                done

                # If the last frame isn't exactly a multiple of the interval, add it
                if [ $(($simulation_time % $interval)) -ne 0 ]; then
                    # Similarly, you can call the command to extract the last frame
                    printf "17\n" | gmx trjconv -s md.tpr -f md_center.xtc -o $frames_dir/frame_${simulation_time}.pdb -b $simulation_time -e $simulation_time
                fi
            else
                sleep 1.0
            fi
        else
            # Round interval to the nearest multiple of 10
            interval=$(awk "BEGIN {print int((($simulation_time / $sim_frames) + 5) / 10) * 10}")

            # Ensure the minimum interval is 10 ps
            if [ "$interval" -lt 10 ]; then
                interval=10
            fi

            # Create frames directory
            frames_dir="frames"
            mkdir -p "$frames_dir"

            # Initialize start time
            start_time=0

            # Extract frames at multiples of 10 ps
            while [ "$start_time" -le "$simulation_time" ]; do
                printf "17\n" | gmx trjconv -s md_center.tpr -f md.xtc -o "$frames_dir/frame_${start_time}.pdb" -b "$start_time" -e "$start_time"
                start_time=$((start_time + interval))
            done

            # Ensure the last frame is included if not a multiple of interval
            last_frame=$(( (simulation_time / 10) * 10 ))  # Round down to nearest 10
            if [ "$last_frame" -ne "$start_time" ]; then
                printf "17\n" | gmx trjconv -s md_center.tpr -f md.xtc -o "$frames_dir/frame_${last_frame}.pdb" -b "$last_frame" -e "$last_frame"
            fi
        fi
    fi
}

# Function to run production MD
production_md() {
    echo
    # Check for required files
    if [ ! -f "$project_dir/npt.gro" ]; then
        echo -e ${LIGHT_RED} "npt.gro does not exist.${NC}"
        sleep 2.0
        exit 1
    fi

    if [ ! -f "$project_dir/md.mdp" ]; then
        echo "md.mdp does not exist. Downloading..."
        file_download_name="md.mdp"
        (wget -nc "http://www.mdtutorials.com/gmx/lysozyme/Files/md.mdp") &
        download_loader
    fi

    check_file_exists "$project_dir/md.xtc" || return

    #User input simulation time
    echo -e ${YELLOW}"Do you want to continue with default simulation time (10ns)?"
    echo -e "${LIGHT_PURPLE}[${NC}01${LIGHT_PURPLE}]${NC} Yes, continue"
    echo -e "${LIGHT_PURPLE}[${NC}02${LIGHT_PURPLE}]${NC} No, enter custom value"
    echo
    read -p "Enter your choice [1-2]: " simulation_time
    echo -e ${NC}

    case $simulation_time in
    1) md_nsteps=5000000 ;;
    2)
        read -p "Set simulation time (ns): " md_time_ns
        md_time_ps=$(echo "$md_time_ns * 1000" | bc)
        md_nsteps=$(echo "$md_time_ps / 0.002" | bc)
        ;;
    *)
        echo -e "${LIGHT_RED}Invalid option! Please select between 1 and 3.${NC}"
        sleep 2.0
        return
        ;;
    esac

    # Update nsteps and generate new md.tpr file
    update_simulation_steps

    echo -e ${LIGHT_GREEN}"Preparation DONE!${NC}"

    # Check for any GPU using lspci
    gpu_info=$(lspci | grep -i vga)

    if [[ -n "$gpu_info" ]]; then
        echo "GPU detected:"
        echo "$gpu_info"

        # Check if the GPU is an NVIDIA card and if nvidia-smi is available
        if command -v nvidia-smi &>/dev/null; then
            echo -e ${LIGHT_CYAN} "NVIDIA GPU detected. Running nvidia-smi for details:${NC}"
            nvidia-smi
            sleep 3.0

            # Measure and show time while running the simulation, suppress output
            start_time=$(date +%s) # Get start time
            gmx mdrun -deffnm $project_dir/md -v -nb gpu >/dev/null 2>&1 &
            show_spinner $! "Running MD Simulation"
            end_time=$(date +%s) # Get end time

            elapsed=$((end_time - start_time)) # Calculate elapsed time in seconds
            echo "Elapsed time: $elapsed seconds"
            show_spinner $! "Running MD Simulation on GPU"

        else
            echo -e ${LIGHT_CYAN} "NVIDIA GPU not detected or nvidia-smi command not found. Running simulation on CPU...${NC}"
            sleep 3.0

            # Measure and show time while running the simulation, suppress output
            start_time=$(date +%s) # Get start time
            gmx mdrun -deffnm $project_dir/md -v >/dev/null 2>&1 &
            show_spinner $! "Running MD Simulation"
            end_time=$(date +%s) # Get end time

            elapsed=$((end_time - start_time)) # Calculate elapsed time in seconds
            echo "Elapsed time: $elapsed seconds"
            show_spinner $! "Running MD Simulation on CPU"
        fi
    else
        echo -e ${LIGHT_CYAN}"No GPU detected. Running simulation on CPU..."${NC}
        sleep 3.0

        # Measure and show time while running the simulation, suppress output
        start_time=$(date +%s) # Get start time
        gmx mdrun -deffnm $project_dir/md -v >/dev/null 2>&1 &
        show_spinner $! "Running MD Simulation"
        end_time=$(date +%s) # Get end time

        elapsed=$((end_time - start_time)) # Calculate elapsed time in seconds
        echo "Elapsed time: $elapsed seconds"
        sleep 2.0
    fi
    echo
    result_analyze >/dev/null 2>&1 &
    show_spinner $! "Analyzing results and extracting frames"
    echo
    #Finding Radius of Gyration...
    # if [ ! -f "$project_dir/md_center.xtc" ]; then
    #     echo -e ${LIGHT_RED} "md_center.xtc does not exist.${NC}"
    #     exit 1
    # fi
    # check_file_exists "$project_dir/gyrate.xvg" || return
    # printf "1\n" | gmx gyrate -s $project_dir/md.tpr -f $project_dir/md_center.xtc -o $project_dir/gyrate.xvg >/dev/null 2>&1 || exit 1

    # #Analyzing Hbonds...
    # if [ ! -f "$project_dir/md_center.xtc" ]; then
    #     echo -e ${LIGHT_RED} "md_center.xtc does not exist.${NC}"
    #     exit 1
    # fi
    # check_file_exists "$project_dir/hbnum.xvg" || return
    # check_file_exists "$project_dir/hbdist.xvg" || return
    # printf "1 11\n" |  gmx hbond -f $project_dir/md_center.xtc -s $project_dir/md.tpr -num -dist > /dev/null 2>&1 || exit 1

    # #Analyzing RMSF...
    # if [ ! -f "$project_dir/md_center.xtc" ]; then
    #     echo -e ${LIGHT_RED} "md_center.xtc does not exist.${NC}"
    #     exit 1
    # fi
    # check_file_exists "$project_dir/rmsf.xvg" || return
    # printf "1\n" | gmx rmsf -f $project_dir/md_center.xtc -s $project_dir/md.tpr -o $project_dir/rmsf.xvg >/dev/null 2>&1 || exit 1

    # #Analyzing Temp...
    # if [ ! -f "$project_dir/nvt.edr" ]; then
    #     echo -e ${LIGHT_RED} "nvt.edr does not exist.${NC}"
    #     exit 1
    # fi
    # check_file_exists "$project_dir/temp.xvg" || return
    # printf "17\n" | gmx energy -f $project_dir/nvt.edr -o $project_dir/temp.xvg >/dev/null 2>&1 || exit 1

    # #Analyzing Pressure...
    # if [ ! -f "$project_dir/npt.edr" ]; then
    #     echo -e ${LIGHT_RED} "npt.edr does not exist.${NC}"
    #     exit 1
    # fi
    # check_file_exists "$project_dir/pressure.xvg" || return
    # printf "19\n" | gmx energy -f $project_dir/npt.edr -o $project_dir/pressure.xvg >/dev/null 2>&1 || exit 1

    # #Interaction energy
    # if [ ! -f "$project_dir/ie.mdp" ]; then
    #     echo -e ${LIGHT_RED} "ie.mdp does not exist.${NC}"
    #     exit 1
    # fi
    # check_file_exists "$project_dir/ie.tpr" || return
    # gmx grompp -f $project_dir/ie.mdp -c $project_dir/npt.gro -t $project_dir/npt.cpt -p $project_dir/topol.top -n $project_dir/index.ndx -o $project_dir/ie.tpr >/dev/null 2>&1 || exit 1
    # gmx mdrun -deffnm $project_dir/ie -rerun $project_dir/md_center.xtc -nb cpu >/dev/null 2>&1 || exit 1
    # printf "21 22 0" | gmx energy -f $project_dir/ie.edr -o $project_dir/interaction_energy.xvg >/dev/null 2>&1 || exit 1

    wait
    return
}

avg_stddev(){
    local xvg_file="$1" 
    local unit="$2"
    # Define local colors using tput
    local YELLOW=$(tput setaf 3)  # Set yellow color
    local CYAN=$(tput setaf 6)    # Set cyan color
    local NC=$(tput sgr0)         # Reset color to default

    # Process the file with AWK
    awk -v YELLOW="$YELLOW" -v CYAN="$CYAN" -v NC="$NC" -v unit="$unit" '
    BEGIN {sum=0; sumsq=0; count=0;}
    /^[^@#]/ && NF >= 2 {sum+=$2; sumsq+=$2*$2; count++;}
    END {
        if (count > 0) {
            avg = sum / count;
            stddev = sqrt((sumsq / count) - (avg * avg));
            printf YELLOW "\nAverage: " CYAN "%.4f %s" NC "\n", avg, unit;
            printf YELLOW "Standard Deviation: " CYAN "%.4f %s" NC "\n\n", stddev, unit;
        } else {
            print "No valid data found in RMSF file.";
        }
    }' "$xvg_file"
}

# Function to run analysis
run_analysis() {
    echo
    while true; do
        echo -e "${YELLOW}---------------------------"
        echo -e "       Analysis Menu"
        echo -e "---------------------------${NC}"
        echo "1) RMSD"
        echo "2) RMSF"
        echo "3) Radius of Gyration"
        echo "4) H-Bond"
        echo "5) Energies"
        echo "6) Back to Main Menu"
        echo -e "${YELLOW}---------------------------${NC}"
        echo
        read -p "Enter your choice [1-7]: " analysis_choice

        case $analysis_choice in
        1)
            echo
            echo "Analyzing RMSD values..."
            echo
            xvg_file="$project_dir/rmsd.xvg"
            unit="nm"
            if [ ! -f "$project_dir/rmsd.xvg" ]; then
                if [ ! -f "$project_dir/md_center.xtc" ]; then
                    echo -e ${LIGHT_RED} "md_center.xtc does not exist.${NC}"
                    exit 1
                fi
                check_file_exists "$project_dir/rmsd.xvg" || return
                printf "4 4\n" | gmx rms -s $project_dir/em.tpr -f $project_dir/md_center.xtc -n $project_dir/index.ndx -tu ns -o $project_dir/rmsd.xvg >/dev/null 2>&1 || exit 1
            fi
            xmgrace $project_dir/rmsd.xvg
            avg_stddev "$xvg_file" "$unit"
            ;;
        2)
            echo
            echo "Analyzing RMSF..."
            echo
            xvg_file="$project_dir/rmsf.xvg"
            unit="nm"
            if [ ! -f "$project_dir/rmsf.xvg" ]; then
                if [ ! -f "$project_dir/md_center.xtc" ]; then
                    echo -e ${LIGHT_RED} "md_center.xtc does not exist.${NC}"
                    exit 1
                fi
                check_file_exists "$project_dir/rmsf.xvg" || return
                printf "3\n" | gmx rmsf -f $project_dir/md_center.xtc -s $project_dir/md.tpr -o $project_dir/rmsf.xvg >/dev/null 2>&1 || exit 1
            fi
            xmgrace $project_dir/rmsf.xvg
            avg_stddev "$xvg_file" "$unit"
            ;;
        3)
            echo
            echo "Analyzing Radius of Gyration..."
            echo
            xvg_file="$project_dir/gyrate.xvg"
            unit="nm"
            if [ ! -f "$project_dir/gyrate.xvg" ]; then
                if [ ! -f "$project_dir/md_center.xtc" ]; then
                    echo -e ${LIGHT_RED} "md_center.xtc does not exist.${NC}"
                    exit 1
                fi
                check_file_exists "$project_dir/gyrate.xvg" || return
                printf "1\n" | gmx gyrate -s $project_dir/md.tpr -f $project_dir/md_center.xtc -o $project_dir/gyrate.xvg >/dev/null 2>&1 || exit 1
            fi
            xmgrace $project_dir/gyrate.xvg
            avg_stddev "$xvg_file" "$unit"
            ;;
        4)
            echo
            echo "Analyzing H bonds..."
            echo
            echo "1) No. of H bonds"
            echo "2) Average distance between H bonds"
            echo "3) Back to menu"
            echo
            read -p "Enter your choice [1-3]: " hbond_choice

            case $hbond_choice in
            1)
                echo
                echo "Analyzing No. of H bonds..."
                echo
                xvg_file="$project_dir/hbnum.xvg"
                unit=""
                if [ ! -f "$project_dir/hbnum.xvg" ]; then
                    if [ ! -f "$project_dir/md_center.xtc" ]; then
                        echo -e ${LIGHT_RED} "md_center.xtc does not exist.${NC}"
                        exit 1
                    fi
                    check_file_exists "$project_dir/hbnum.xvg" || return
                    printf "1\n11\n" | gmx hbond -f $project_dir/md_center.xtc -s $project_dir/md.tpr -num -dist >/dev/null 2>&1 || exit 1
                fi
                xmgrace $project_dir/hbnum.xvg
                avg_stddev "$xvg_file" "$unit"
                ;;
            2)
                echo
                echo "Analyzing Average distance between H bonds..."
                echo
                xvg_file="$project_dir/hbdist.xvg"
                unit=""
                if [ ! -f "$project_dir/hbdist.xvg" ]; then
                    if [ ! -f "$project_dir/md_center.xtc" ]; then
                        echo -e ${LIGHT_RED} "md_center.xtc does not exist.${NC}"
                        exit 1
                    fi
                    check_file_exists "$project_dir/hbdist.xvg" || return
                    printf "1\n11\n" | gmx hbond -f $project_dir/md_center.xtc -s $project_dir/md.tpr -num -dist >/dev/null 2>&1 || exit 1
                fi
                xmgrace $project_dir/hbdist.xvg
                avg_stddev "$xvg_file" "$unit"
                ;;
            3)
                echo
                echo "Returning to Main Menu..."
                return
                ;;
            *)
                echo "${LIGHT_RED}Invalid option! Please select between 1 and 3.${NC}"
                sleep 1.0
                ;;
            esac
            ;;
        5)
            echo
            echo "Analyzing Energies..."
            echo
            echo "1) Temperature"
            echo "2) Pressure"
            echo "3) Interaction Energy"
            echo "4) Back to menu"
            echo
            read -p "Enter your choice [1-4]: " energy_choice

            case $energy_choice in
            1)
                echo
                echo "Temperature..."
                echo
                xvg_file="$project_dir/temp.xvg"
                unit="K"
                if [ ! -f "$project_dir/temp.xvg" ]; then
                    if [ ! -f "$project_dir/nvt.edr" ]; then
                        echo -e ${LIGHT_RED} "nvt.edr does not exist.${NC}"
                        exit 1
                    fi
                    check_file_exists "$project_dir/temp.xvg" || return
                    printf "17\n" | gmx energy -f $project_dir/nvt.edr -o $project_dir/temp.xvg >/dev/null 2>&1 || exit 1
                fi
                xmgrace $project_dir/temp.xvg
                avg_stddev "$xvg_file" "$unit"
                ;;
            2)
                echo
                echo "Pressure..."
                echo
                xvg_file="$project_dir/pressure.xvg"
                unit="nm"
                if [ ! -f "$project_dir/pressure.xvg" ]; then
                    if [ ! -f "$project_dir/npt.edr" ]; then
                        echo -e ${LIGHT_RED} "npt.edr does not exist.${NC}"
                        exit 1
                    fi
                    check_file_exists "$project_dir/pressure.xvg" || return
                    printf "19\n" | gmx energy -f $project_dir/npt.edr -o $project_dir/pressure.xvg >/dev/null 2>&1 || exit 1
                fi
                xmgrace $project_dir/pressure.xvg
                avg_stddev "$xvg_file" "$unit"
                ;;
            3)
                echo
                echo "Interaction Energies..."
                echo
                xvg_file="$project_dir/interaction_energy.xvg"
                unit="kJ/mol"
                if [ ! -f "$project_dir/interaction_energy.xvg" ]; then
                    if [ ! -f "$project_dir/ie.mdp" ]; then
                        echo -e ${LIGHT_RED} "ie.mdp does not exist.${NC}"
                        exit 1
                    fi
                    check_file_exists "$project_dir/ie.tpr" || return
                    gmx grompp -f $project_dir/ie.mdp -c $project_dir/npt.gro -t $project_dir/npt.cpt -p $project_dir/topol.top -n $project_dir/index.ndx -o $project_dir/ie.tpr >/dev/null 2>&1 || exit 1
                    gmx mdrun -deffnm $project_dir/ie -rerun $project_dir/md_center.xtc -nb cpu >/dev/null 2>&1 || exit 1
                    printf "21 22 0" | gmx energy -f $project_dir/ie.edr -o $project_dir/interaction_energy.xvg >/dev/null 2>&1 || exit 1
                fi
                xmgrace $project_dir/interaction_energy.xvg
                avg_stddev "$xvg_file" "$unit"
                ;;
            4)
                echo
                echo "Returning to Main Menu..."
                return
                ;;
            *)
                echo -e "${LIGHT_RED}Invalid option! Please select between 1 and 3.${NC}"
                sleep 1.0
                ;;
            esac
            ;;
        6)
            echo
            echo "Returning to Main Menu..."
            return
            ;;
        *)
            echo "${LIGHT_RED}Invalid option! Please select between 1 and 7.${NC}"
            sleep 1.0
            ;;
        esac
    done
}

banner() {
    # Main script loop
    clear
    echo
    # Print the colored ASCII art
    echo -e "${LIGHT_RED}  __________________    _________   ____.______________      ${RESET}"
    echo -e "${LIGHT_RED} /  _____/\\______   \\  /  _  \\   \\ /   /|   \\__    ___/${RESET}__.__. "
    echo -e "${LIGHT_RED}/   \\  ___ |       _/ /  /_\\  \\   Y   / |   | |    | ${RESET}<   |  | "
    echo -e "${LIGHT_RED}\\    \\_\\  \\|    |   \\/    |    \\     /  |   | |    |  ${RESET}\\___  | "
    echo -e "${LIGHT_RED} \\______  /|____|_  /\\____|__  /\\___/   |___| |____|  ${RESET}/ ____| "
    echo -e "${LIGHT_RED}        \\/        \\/         \\/                       ${RESET}\\/      "
    echo
    echo -e "${WHITE}  [${LIGHT_RED}G${NC}ROMACS ${LIGHT_RED}R${NC}un ${LIGHT_RED}A${NC}nalysis & ${LIGHT_RED}V${NC}isualization ${LIGHT_RED}I${NC}nterface ${LIGHT_RED}T${NC}ool -y]${NC}"
    echo
}

main_menu() {
    while true; do
        echo
        echo -e "${YELLOW}------------------------------------"
        echo -e "             Main Menu"
        echo -e "------------------------------------${NC}"
        echo -e "${LIGHT_PURPLE}[${NC}01${LIGHT_PURPLE}]${NC} Retrieve Complex Molecules"
        echo -e "${LIGHT_PURPLE}[${NC}02${LIGHT_PURPLE}]${NC} Prepare Protein Topology"
        echo -e "${LIGHT_PURPLE}[${NC}03${LIGHT_PURPLE}]${NC} Prepare Ligand Topology"
        echo -e "${LIGHT_PURPLE}[${NC}04${LIGHT_PURPLE}]${NC} Define box and solvate the system"
        echo -e "${LIGHT_PURPLE}[${NC}05${LIGHT_PURPLE}]${NC} Add ions"
        echo -e "${LIGHT_PURPLE}[${NC}06${LIGHT_PURPLE}]${NC} Energy minimization"
        echo -e "${LIGHT_PURPLE}[${NC}07${LIGHT_PURPLE}]${NC} Equilibrium"
        echo -e "${LIGHT_PURPLE}[${NC}08${LIGHT_PURPLE}]${NC} Production MD"
        echo -e "${LIGHT_PURPLE}[${NC}09${LIGHT_PURPLE}]${NC} Analysis"
        echo -e "${LIGHT_PURPLE}[${NC}10${LIGHT_PURPLE}]${NC} ${LIGHT_RED}Exit${NC}"
        echo -e "${YELLOW}------------------------------------${NC}"

        choice=$(prompt_user "Enter your choice [1-9]: ")

        case $choice in
        1) retrieve_complex ;;
        2) prepare_protein_topology ;;
        3) prepare_ligand_topology ;;
        4) define_box_and_solvate ;;
        5) add_ions ;;
        6) energy_minimization ;;
        7) equilibrium ;;
        8) production_md ;;
        9) run_analysis ;;
        10)
            echo -e "${LIGHT_YELLOW}Thanks for using GRAVITy!${NC}"
            echo "Exiting..."
            echo
            exit 0
            ;;
        *)
            echo -e "${LIGHT_RED}Invalid option! Please select between 1 and 11.${NC}"
            sleep 1.0
            ;;
        esac
    done
}

banner
check_internet
echo
check_dependencies
echo -e "${LIGHT_CYAN}Simulation type: Protein-Ligand Complex${NC}"
echo
# Main script loop
echo "Welcome to the GROMACS simulation"
echo
echo "Please keep your docked protein and ligand complex ready in the working directory."
echo "Please process your protein.pdbqt by removing water molecules or any HETATM's available"
echo "and convert it into protein.pdb format"
echo
main_menu
